<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/cgi-bin/koha/opac-main.pl">[% 'Home' | gettext %]</a></li>
    <li class="breadcrumb-item"><a href="/cgi-bin/koha/plugins/plugins-home.pl">[% 'Plugins' | gettext %]</a></li>
    <li class="breadcrumb-item active"><a href="#">[% 'Room Reservations' | gettext %]</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="#">[% 'Configuration' | gettext %]</a></li>
  </ol>
</nav>