<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/cgi-bin/koha/opac-main.pl">Home</a></li>
    <li class="breadcrumb-item"><a href="/cgi-bin/koha/plugins/plugins-home.pl">Plugins</a></li>
    <li class="breadcrumb-item active"><a href="#">Room Reservations</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="#">Configuration</a></li>
  </ol>
</nav>